sudo: false

language: node_js

node_js:
- '7.10'

addons:
  artifacts: true
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - fakeroot
    - g++-4.8
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev

branches:
  only:
  - master
  - "/ci-.*/"
  - "/stable.*/"

matrix:
  include:
  - os: linux
    env: CC=gcc-4.8 CXX=g++-4.8 DEBUG="electron-packager:*"
  - os: osx
    env: CC=clang CXX=clang++ SIGN_BUILD=true DEBUG="electron-packager:*"

before_install:
- openssl aes-256-cbc -K $encrypted_faf2708e46e2_key -iv $encrypted_faf2708e46e2_iv
  -in app/build/resources/certs.tar.enc -out app/build/resources/certs.tar -d;
- mkdir app/build/resources/certs;
- tar xvf app/build/resources/certs.tar --directory=app/build/resources/;
- source app/build/resources/certs/mac/set_unix_env.sh;

script:
- npm run build

addons:
  artifacts:
    working_dir: app/dist
    target_paths: builds/${TRAVIS_COMMIT:0:8}/${TRAVIS_OS_NAME}
    paths:
    - Merani.dmg
    - Merani.zip
    - "*.rpm"
    - "*.deb"

cache:
  directories:
  - node_modules
  - app/node_modules