sudo: true

git:
  submodules: false

language: node_js

node_js:
- '6.9'

addons:
  artifacts:
    working_dir: app/dist
    target_paths: client/${TRAVIS_COMMIT:0:8}/${TRAVIS_OS_NAME}
    permissions: public-read
    paths:
    - mailsync
    - mailsync.dSYM.zip
    - Merani.dmg
    - Merani.zip
    - $(find . -type f -name *.deb | tr "\n" ":")
    - $(find . -type f -name *.rpm | tr "\n" ":")
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - cmake
    - fakeroot
    - g++-5
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm
    - autoconf
    - automake
    - libtool
    - libctemplate-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - libxext-dev
    - libsasl2-dev
    - libssl-dev
    - libtidy-dev
    - libxtst-dev
    - libxkbfile-dev
    - libglib2.0-dev
    - libxml2-dev
    - uuid-dev

branches:
  only:
  - master
  - "/ci-.*/"
  - "/stable.*/"

matrix:
  include:
  - os: linux
    env: CC=gcc-5 CXX=g++-5
  - os: osx
    osx_image: xcode8.3
    env: CC=clang CXX=clang++ SIGN_BUILD=true

before_install:
# Decrypt and uncompress code signing certs, etc.
- openssl aes-256-cbc -K $encrypted_faf2708e46e2_key -iv $encrypted_faf2708e46e2_iv
  -in app/build/resources/certs.tar.enc -out app/build/resources/certs.tar -d;
- mkdir app/build/resources/certs;
- tar xvf app/build/resources/certs.tar --directory=app/build/resources/;
- source app/build/resources/certs/mac/set_unix_env.sh;
# Checkout the (currently private) C++ Mailsync codebase
- GIT_SSH_COMMAND='ssh -i app/build/resources/certs/mailsync-deploy-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  SSH_ASKPASS=/Users/travis/build/Foundry376/Merani/app/build/resources/certs/ssh-askpass-fix
  DISPLAY=nothing:0
  git submodule update --init mailsync

script:
- mailsync/build.sh
- DEBUG=electron-packager npm run build

cache:
  directories:
  - node_modules
  - app/node_modules
  - /tmp/mailsync-build-deps