sudo: false

git:
  submodules: false

language: node_js

node_js:
- '6.9'

addons:
  artifacts:
    working_dir: app/dist
    target_paths: client/${TRAVIS_COMMIT:0:8}/${TRAVIS_OS_NAME}
    permissions: public-read
    paths:
    - ../MailSync
    - Merani.dmg
    - Merani.zip
    - $(find . -type f -name *.deb | tr "\n" ":")
    - $(find . -type f -name *.rpm | tr "\n" ":")
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - clang
    - fakeroot
    - g++-4.8
    - git
    - libgnome-keyring-dev
    - xvfb
    - rpm
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev

branches:
  only:
  - master
  - "/ci-.*/"
  - "/stable.*/"

matrix:
  include:
  - os: linux
    env: CC=gcc-4.8 CXX=g++-4.8 DEBUG="electron-packager:*"
  - os: osx
    env: CC=clang CXX=clang++ SIGN_BUILD=true DEBUG="electron-packager:*"

before_install:
- openssl aes-256-cbc -K $encrypted_faf2708e46e2_key -iv $encrypted_faf2708e46e2_iv
  -in app/build/resources/certs.tar.enc -out app/build/resources/certs.tar -d;
- mkdir app/build/resources/certs;
- tar xvf app/build/resources/certs.tar --directory=app/build/resources/;
- source app/build/resources/certs/mac/set_unix_env.sh;

script:
# Checkout and build the (currently private) C++ codebase
- GIT_SSH_COMMAND='ssh -i app/build/resources/mailsync-deploy-key' git submodule update mailsync
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -scheme MailSync -configuration Release; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "TODO"; fi
# Build and package the Merani Electron application
- npm run build

cache:
  directories:
  - node_modules
  - app/node_modules