name: mailspring
adopt-info: mailspring

confinement: strict
base: core18

architectures:
  - build-on: amd64

parts:
  mailspring:
    plugin: nil
    override-pull: |
      deb="$(ls $SNAPCRAFT_PROJECT_DIR/app/dist/mailspring-*.deb)"
      snapcraftctl set-version "$(basename "$deb" | grep -Eo "[0-9]+.[0-9]+.[0-9]+")"
      dpkg -x "$deb" "$SNAPCRAFT_PART_SRC"
    override-build: |
      cp -a "$SNAPCRAFT_PART_SRC"/* "$SNAPCRAFT_PART_INSTALL"
      snapcraftctl build
      sed -i 's|Icon=mailspring|Icon=/usr/share/pixmaps/mailspring\.png|' \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/Mailspring.desktop
    prime:
      - -usr/share/mailspring/chrome-sandbox
    parse-info: [usr/share/appdata/mailspring.appdata.xml]
    stage-packages:
      - libnspr4
      - libnss3
      - libxkbfile1
      - libxss1

apps:
  mailspring:
    command: usr/bin/mailspring --no-sandbox
    common-id: mailspring
    desktop: usr/share/applications/Mailspring.desktop
    extensions: [gnome-3-34]
    environment:
      HOME: $SNAP_USER_COMMON
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - avahi-observe
      - browser-support
      - cups-control
      - gsettings
      - opengl
      - home
      - desktop
      - desktop-legacy
      - mount-observe
      - network
      - network-bind
      - network-observe
      - password-manager-service
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - unity7
      - x11
